server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host:             unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          # Ne collecter que les containers du projet ciblé
          # Modifier COMPOSE_PROJECT dans le .env
          - name:   label
            values: ["com.docker.compose.project=${COMPOSE_PROJECT:-mon-projet}"]

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex:         /(.*)
        target_label:  container

      - source_labels: [__meta_docker_compose_service]
        target_label:  service

    pipeline_stages:
      # Tenter de parser le log comme du JSON (backend prod)
      - json:
          expressions:
            level:       level
            message:     message
            requestId:   requestId
            username:    username
            clientApp:   clientApp

      - labels:
          level:
          service:
          container:

      - structured_metadata:
          requestId:  requestId
          username:   username
          clientApp:  clientApp
